#!/usr/bin/env python3
"""Generate src/bmd_run/incar_tags.py from pymatgen's incar_parameters.json.

The generated module is a closed vocabulary of VASP INCAR tag names, their
syntactic value types, and the enumerated words for string-valued tags. The
client uses it only to parse Compute's INCAR preview into typed values; it
makes no decision about which tags or values are appropriate.

usage:
    python tools/generate_incar_tags.py /path/to/pymatgen/io/vasp/incar_parameters.json

The file is read as plain JSON; pymatgen is not imported. The generated module
records the input's SHA-256 so a reviewer can reproduce it.
"""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "src" / "bmd_run" / "incar_tags.py"
TYPES = {"bool": "bool", "int": "int", "float": "float", "list": "list", "str": "str", "bool | str": "bool_or_word"}


def main(argv) -> int:
    if len(argv) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    source = Path(argv[0])
    raw = source.read_bytes()
    table = json.loads(raw)
    lines = [
        '"""GENERATED by tools/generate_incar_tags.py - do not edit by hand.',
        "",
        "Closed vocabulary of VASP INCAR tags: syntactic value type and, for word-valued",
        "tags, the permitted words. Source: pymatgen 2026.5.4 (pinned in BMD Compute",
        "v1.0.0 constraints) pymatgen/io/vasp/incar_parameters.json,",
        f"sha256 {hashlib.sha256(raw).hexdigest()}.",
        "",
        "Types: bool, int, float, list (numbers/logicals, N*value allowed), word (only",
        "the listed words), bool_or_word, opaque (free text: never reported).",
        '"""',
        "",
        "from types import MappingProxyType",
        "",
        "TAGS = MappingProxyType({",
    ]
    for tag in sorted(table):
        entry = table[tag]
        kind = TYPES[entry["type"]]
        words = tuple(str(v) for v in entry.get("values", ()) if isinstance(v, str))
        if kind == "str":
            kind = "word" if words else "opaque"
        if kind not in ("word", "bool_or_word"):
            words = ()
        lines.append(f"    {tag!r}: ({kind!r}, {words!r}),")
    lines.append("})")
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {TARGET.relative_to(ROOT)} ({len(table)} tags)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
